version: '3.9'

services:

  web:
    build: ./
    ports:
      - "8080:8080"
    command: dotnet run
    volumes:
      - .:/my_app
    networks:
        - boards
    depends_on:
        - sql_server
  serilog_seq:
    image: datalust/seq:latest
    ports:
        - "5341:5341"
        - "80:80"
    volumes:
        - ./logs:/data
    environment:
        ACCEPT_EULA: Y
        SEQ_FIRSTRUN_ADMINPASSWORDHASH: 1q2w3e4r!!
    depends_on: 
        - web
        - sql_server
    networks:
        - boards
  sql_server:
     image: mcr.microsoft.com/azure-sql-edge
     ports:
       - "14330:14330"
     environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: 1q2w3e4r!!
     networks:
        - boards
networks:
  boards:
   driver: bridge